---
title: "hw1_agreement"
author: "Katya Protsenyuk"
date: '12 С„РµРІСЂР°Р»СЏ 2018 Рі '
output: html_document
---

### 1.1 
```{r}
library(tidyverse)
library(irr)

df <- read_csv("https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/katyaprotsenyuk/hw1_agreement/hw1_1_zilo_class.csv")

head(df)

df %>% 
  distinct(stimulus_source,translation_en) %>% 
  count(stimulus_source)

```


### 1.2
```{r}

df %>% 
  select(s_id, translation_en, class) %>% 
  spread(key = s_id, value = class) ->
  df_short
head(df_short)

agree(df_short[,-1])

```

### 1.3
```{r}

kappa2(df_short[,c(8, 12)])

```

### 1.4
```{r}

kappam.fleiss(df_short[,-c(1)])

```

### 1.5
```{r}
На материале зиловского диалекта андийского языка был проведен эксперимент, в ходе которого проверярялось наличие вариативности в отнесении исконной и заимствованной лексики к одному из двух классов для неодушевленных предметов. Каждый участник эксперимента определял, к какому из двух классов относится каждое слово-стимул.
Участники сделали идентичные суждения в 73% случаев (возможность случайного совпадения /расхождения суждений не учитывается). Мера согласия между двумя оценщиками, проверенная с помощью Каппы Коэна, составляет 0,865, что по [Landis, Koch 1977] является практически идеальным согласием. Мера согласия оценщиков по Каппе Фляйса составляет 0,842. 
Можно сделать вывод о наличии невысокой вариативности в отнесении исконной и заимствованной лексики к одному из двух классов для неодушевленных предметов.
```


### 2.1

```{r}

df2 <- read_csv("https://raw.githubusercontent.com/agricolamz/2018_data_analysis_for_linguists/master/data/students/katyaprotsenyuk/hw1_agreement/hw1_2_verbs.csv")

head(df2)

df2 %>% 
  distinct(SubjectCode) %>% 
  count()

```


### 2.2
```{r}

df2 %>%
  group_by(WordType, Gender) %>% 
  summarise(mean = mean(GivenScore))

```

### 2.3
```{r}

df2 %>% 
  select(SubjectCode, Stimulus, GivenScore, Prefix) %>% 
  spread(key = SubjectCode, value = GivenScore) ->
  df2_short

df2_short <-na.omit(df2_short) #у меня появляются NA только если добавить Prefix, а если делать по аналогии с 1.2, то никаких NA нет и получается 60 субъектов

agree(df2_short[,-c(1:2)])

```

### 2.4
```{r}

kappam.fleiss(df2_short[,-c(1:2)])

```

### 2.5
```{r}

icc(df2_short[,-c(1:2)], model = "twoway", type = "agreement")

```

### 2.6


```{r}

tablica <- as.table(cor(df2_short[,-c(1:2)], method = "kendall"))

```

